---
#####
# Surviva Game Plugin
# Made By: Andre_The_Gamer
#####


##
# Arena's #
##

Player_Join_Server: Welcome To My Server


Lobby-World: Lobby    // This will be where player's get teleported after they die / win match.
Match-World: SG   // The world the plugin will use to teleport the player to the arena.

Min-Player: 2 // Cannot be changed! 'YET"
Max-Player: 24 // Cannot be changed! 'YET"


# Stand Where you wan't to set spawn and do /xyz and add the number's in config
# Add The same line for more player's
Spawns:
- 12      // Edit the number's
- 121
- 121


---
